name: NoEnchantPlugin
version: '1.0'
main: me.loyalty.noenchant.NoEnchantPlugin
api-version: '1.21'
author: LoyaltyMC
description: Disable all enchantments in the server.
commands:
  protectitem:
    description: ចាក់សោការពារ Item មិនឱ្យលុប Enchant
    permission: noenchant.admin
permissions:
  noenchant.admin:
    description: Allows using the protectitem command
    default: op
